//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.WeatherServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherServiceReference.IWeather")]
    public interface IWeather {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeather/getLatLong", ReplyAction="http://tempuri.org/IWeather/getLatLongResponse")]
        System.Collections.Generic.Dictionary<string, string> getLatLong(string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeather/getLatLong", ReplyAction="http://tempuri.org/IWeather/getLatLongResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> getLatLongAsync(string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeather/getWeatherData", ReplyAction="http://tempuri.org/IWeather/getWeatherDataResponse")]
        System.Collections.Generic.Dictionary<string, string> getWeatherData(string lat, string lon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeather/getWeatherData", ReplyAction="http://tempuri.org/IWeather/getWeatherDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> getWeatherDataAsync(string lat, string lon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherChannel : WebApplications.WeatherServiceReference.IWeather, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherClient : System.ServiceModel.ClientBase<WebApplications.WeatherServiceReference.IWeather>, WebApplications.WeatherServiceReference.IWeather {
        
        public WeatherClient() {
        }
        
        public WeatherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> getLatLong(string zipCode) {
            return base.Channel.getLatLong(zipCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> getLatLongAsync(string zipCode) {
            return base.Channel.getLatLongAsync(zipCode);
        }
        
        public System.Collections.Generic.Dictionary<string, string> getWeatherData(string lat, string lon) {
            return base.Channel.getWeatherData(lat, lon);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> getWeatherDataAsync(string lat, string lon) {
            return base.Channel.getWeatherDataAsync(lat, lon);
        }
    }
}
