//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplications.CrimeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrimeReference.ICrime")]
    public interface ICrime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrime/getCrimeData", ReplyAction="http://tempuri.org/ICrime/getCrimeDataResponse")]
        System.Collections.Generic.Dictionary<string, string> getCrimeData(string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrime/getCrimeData", ReplyAction="http://tempuri.org/ICrime/getCrimeDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> getCrimeDataAsync(string zipCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrimeChannel : WebApplications.CrimeReference.ICrime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrimeClient : System.ServiceModel.ClientBase<WebApplications.CrimeReference.ICrime>, WebApplications.CrimeReference.ICrime {
        
        public CrimeClient() {
        }
        
        public CrimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> getCrimeData(string zipCode) {
            return base.Channel.getCrimeData(zipCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> getCrimeDataAsync(string zipCode) {
            return base.Channel.getCrimeDataAsync(zipCode);
        }
    }
}
